//Coin Listings related
export const GET_LISTINGS_SUCCESS = 'GET_LISTINGS_SUCCESS';
export const GET_LISTINGS_FAILED = 'GET_LISTINGS_FAILED';
//Currency Information
export const GET_CRYPTOCURRENCY_SUCCESS = 'GET_CRYPTOCURRENCY_SUCCESS';
export const GET_CRYPTOCURRENCY_FAILED = 'GET_CRYPTOCURRENCY_FAILED';
